hold_out: 1
batch_size: 1
update_rate: 0.1
gen_optim_args:
- 0.0001
- - 0.9
  - 0.999
dis_optim_args:
- 0.0001
- - 0.9
  - 0.999
gen_iter: 5
dis_iter: 10
max_norm_net: .inf
max_norm_gen: .001
max_norm_dis: .001
loss_str: "cross_entropy"
timesteps: 200
curriculum:
- - 20000
  - 200
no_cv: False
rule_class: "LocalMLP"
rule_class_args:
  n_presyn_neur: 3
  n_postsyn_neur: 1
dis_type: "dis" # dis, supervised
optimizer_class: "CurriculumLearning"
track_score: False
score_funcn: "pc_norm" # pc_norm, must be same as loss_str for dis_type = supervised
track_weight: True
track_params: True
track_output: False
path_to_data: "../data/oja_net_small/"
init_from_supervised: False
path_to_supervised: None
init_gen_from_previous: False
path_to_previous_gen: None
init_dis_from_previous: False
path_to_previous_dis: None
